model:
  name: nvidia/Qwen3.6-35B-A3B-NVFP4
  providers:
    athena-vllm:
      enabled: true
      provider_type: openai
      baseURL: "https://vllm.athena.cibertrs.cloud/v1"
      models:
        nvidia/Qwen3.6-35B-A3B-NVFP4:
          name: "Qwen3.6"
          tool_call: true
          model_context_length: 131072
          max_tokens: 65536
