{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hades.fullname" . }}-dashboard
  labels: {{- include "hades.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.basicAuth.existingSecret | default (printf "%s-dashboard-basic-auth" (include "hades.fullname" .)) }}
    nginx.ingress.kubernetes.io/auth-realm: "Hades dashboard - authentication required"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-dashboard-tls" (include "hades.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "hades.fullname" . }}-dashboard
                port:
                  number: {{ .Values.dashboard.port }}
{{- end }}
